#pragma once

enum ePackageRecovSend
{
	ADMINS_CMD = -18,


	RPC_SERVER_VEHICLE_CAR_POSSITIONS	= 300,
	RPC_VEHICLE_SPAWN					= 301,
	RPC_VEHICLE_ID_DEATCH				= 302,

	PLAYER_ACTOR_NEW_POSSITIONS = 7,
	UNKNOW_PRMS = 666
};
